# Generated by Django 4.2.19 on 2025-03-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_allergy_description_alter_allergy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='report_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
