branch-defaults:
  main:
    environment: AllergyAnalyzerSystem-env
environment-defaults:
  AllergyAnalyzerSystem-env:
    branch: null
    repository: null
global:
  application_name: Allergy_Analyzer_System
  default_ec2_keyname: Yashashwini_allergy_analyzer
  default_platform: Python 3.9
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
