name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pushes to the main branch

jobs:
  source:
    name: Source Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  build:
    name: Build Stage
    runs-on: ubuntu-latest
    needs: source  #runs only after source is completed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      - name: Create and Activate Virtual Environment
        run: |
          python -m venv env
          source env/bin/activate

      - name: Install Dependencies
        run: |
          source env/bin/activate
          pip install -r requirements.txt
          pip install pylint
        
      - name: Run Pylint
        run: |
          source env/bin/activate
          pylint aws_services/ lambda_package/ user_management/

      - name: Run Django Migrations
        run: |
          source env/bin/activate
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Tests
        run: |
          source env/bin/activate
          python manage.py test

      - name: Package Django App
        run: |
          source env/bin/activate
          mkdir packaged_app
          cp -r allergy_analyzer/ packaged_app/
          cp manage.py packaged_app/
          zip -r packaged_app.zip packaged_app
