name: Deploy Allergy Analyzer

on:
  push:
    branches:
      - main  # Runs CI/CD on every push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC-based authentication, helps in securing the AWS secret keys
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Python Dependencies
        run: |
          pip install pylint
          pip install -r requirements.txt  # Ensure all dependencies are installed

      - name: Run Pylint Tests
        run: |
          pylint aws_services/ lambda_package/ user_management/ 

      - name: Deploy AWS Lambda
        run: |
          python create_lambda.py
          python deploy_lambda.py
          
      - name: Deploy Other AWS Services (S3, SQS, SNS, DynamoDB)
        run: |
          cd aws_services
          python s3_setup.py
          python sqs_sns_setup.py
          python dynamodb_setup.py
